name: Release Extension

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip extension
        run: |
          cd extension
          zip -r ../extension.zip ./*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.zip
          generate_release_notes: true
